version: "3"
services:
  beautifierbot:
    container_name: beautifierbot
    image: beautifierbot
    restart: always
    build: ./Beautifier
    links:
      - mongo
  groupmentionsbot:
    container_name: groupmentionsbot
    image: groupmentionsbot
    restart: always
    build: ./GroupMentionsBot
    links:
      - mongo
  toxmodbot:
    container_name: toxmodbot
    image: toxmodbot
    restart: always
    build: ./ToxMod
    links:
      - mongo
  wordenhancerbot:
    container_name: wordenhancerbot
    image: wordenhancerbot
    restart: always
    build: ./WordEnhancerBot
    links:
      - mongo
  magiceraser:
    container_name: magiceraser
    image: magiceraser
    restart: always
    build: ./MagicEraser
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
  # voicebot:
  #   container_name: voicebot
  #   image: voicebot
  #   restart: always
  #   build: ./VoiceSpeaker
  #   links:
  #     - mongo
  # alexbot:
  #   container_name: alexbot
  #   image: alexbot
  #   restart: always
  #   build: ./AlexBot
  #   links:
  #     - mongo
